"""emisores: periodicidad_consolidacion (g5b-kc)

Revision ID: 02c2b3025be2
Revises: 72d545d1cbfe
Create Date: 2026-09-18 03:53:33.244219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c2b3025be2'
down_revision: Union[str, Sequence[str], None] = '72d545d1cbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('periodicidad_consolidacion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisores', 'periodicidad_consolidacion')
    # ### end Alembic commands ###
