"""agregar tabla negocios y emisores.negocio_id nullable (#15)

Revision ID: 222cf1fd94f6
Revises: a8cfcf493156
Create Date: 2026-08-06 18:24:31.859922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222cf1fd94f6'
down_revision: Union[str, Sequence[str], None] = 'a8cfcf493156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('negocio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_emisores_negocio_id'), 'emisores', ['negocio_id'], unique=False)
    op.create_foreign_key(None, 'emisores', 'negocios', ['negocio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emisores', type_='foreignkey')
    op.drop_index(op.f('ix_emisores_negocio_id'), table_name='emisores')
    op.drop_column('emisores', 'negocio_id')
    # ### end Alembic commands ###
