"""agregar modificado_por_rfc a emisores

Revision ID: 264eee14da7c
Revises: 86ec365e82b2
Create Date: 2026-08-26 23:30:40.659368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264eee14da7c'
down_revision: Union[str, Sequence[str], None] = '86ec365e82b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('modificado_por_rfc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisores', 'modificado_por_rfc')
    # ### end Alembic commands ###
