"""emisores hora_cierre_automatico g7imYM pieza1

Revision ID: 2cce7e6ba51e
Revises: 86da81490e2f
Create Date: 2026-09-18 22:53:31.064795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cce7e6ba51e'
down_revision: Union[str, Sequence[str], None] = '86da81490e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('hora_cierre_automatico', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisores', 'hora_cierre_automatico')
    # ### end Alembic commands ###
