"""agregar tabla notificaciones

Revision ID: 308afdadaa4d
Revises: cbd62825972e
Create Date: 2026-09-14 20:48:12.026354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '308afdadaa4d'
down_revision: Union[str, Sequence[str], None] = 'cbd62825972e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('periodo', sa.String(length=7), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'tipo', 'periodo', name='uq_notificacion_negocio_tipo_periodo')
    )
    op.create_index(op.f('ix_notificaciones_negocio_id'), 'notificaciones', ['negocio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_negocio_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    # ### end Alembic commands ###
