"""agregar logo_url y color_primario a negocios

Revision ID: 455d9f843f76
Revises: 308afdadaa4d
Create Date: 2026-09-14 21:45:19.057976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455d9f843f76'
down_revision: Union[str, Sequence[str], None] = '308afdadaa4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('negocios', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('negocios', sa.Column('color_primario', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('negocios', 'color_primario')
    op.drop_column('negocios', 'logo_url')
    # ### end Alembic commands ###
