"""solicitudes_descarga: mensaje_sat verbatim del SAT (zg55DWY paso 6)

Revision ID: 4af7f6b8bbbd
Revises: c6194443a5e4
Create Date: 2026-09-10 00:16:27.292255

Autogenerada (alembic revision --autogenerate) contra postgres_admin en
c6194443a5e4. Una sola operacion: ADD COLUMN mensaje_sat TEXT NULL sobre
solicitudes_descarga (tabla vacia, sin backfill). Guarda el texto libre
'Mensaje' que devuelve el SAT junto al cod_estatus, verbatim, para
mostrarlo al usuario sin hard-codear la redaccion. Sin drift sobre
ninguna otra tabla.
NO aplicada todavia (pendiente rebuild del contenedor + confirmacion).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af7f6b8bbbd'
down_revision: Union[str, Sequence[str], None] = 'c6194443a5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_descarga', sa.Column('mensaje_sat', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_descarga', 'mensaje_sat')
    # ### end Alembic commands ###
