"""efirma multi-tenant: efirmas, solicitudes_descarga, paquetes_descarga (zg55DWY)

Revision ID: 4f1c844bb8c3
Revises: c176eed5fc42
Create Date: 2026-09-09 01:37:24.028889

Autogenerada (alembic revision --autogenerate) contra postgres_admin en
c176eed5fc42. Solo agrega 3 tablas nuevas - no toca ninguna existente.
Revisada: el diff generado contenia exactamente estas 3 create_table + sus
indices/FKs, sin drift sobre negocios/emisores/clientes/series_folios.
NO aplicada todavia (pendiente confirmacion + EFIRMA_MASTER_KEY real).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1c844bb8c3'
down_revision: Union[str, Sequence[str], None] = 'c176eed5fc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('efirmas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rfc_titular', sa.String(length=13), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('cert_base64', sa.Text(), nullable=False),
    sa.Column('key_base64_cifrado', sa.Text(), nullable=False),
    sa.Column('password_cifrado', sa.Text(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('reemplazada_por_id', sa.Integer(), nullable=True),
    sa.Column('destruida_at', sa.DateTime(), nullable=True),
    sa.Column('creado_por_rfc', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reemplazada_por_id'], ['efirmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efirmas_negocio_id'), 'efirmas', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_efirmas_rfc_titular'), 'efirmas', ['rfc_titular'], unique=False)
    op.create_table('solicitudes_descarga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('efirma_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=False),
    sa.Column('id_solicitud_sat', sa.String(length=40), nullable=True),
    sa.Column('estado_solicitud', sa.SmallInteger(), nullable=False),
    sa.Column('cod_estatus', sa.String(length=5), nullable=True),
    sa.Column('numero_cfdis', sa.Integer(), nullable=True),
    sa.Column('solicitado_por_rfc', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['efirma_id'], ['efirmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_descarga_efirma_id'), 'solicitudes_descarga', ['efirma_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_descarga_id_solicitud_sat'), 'solicitudes_descarga', ['id_solicitud_sat'], unique=True)
    op.create_index(op.f('ix_solicitudes_descarga_negocio_id'), 'solicitudes_descarga', ['negocio_id'], unique=False)
    op.create_table('paquetes_descarga',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('id_paquete_sat', sa.String(length=45), nullable=False),
    sa.Column('descargado', sa.Boolean(), nullable=False),
    sa.Column('ruta_almacenamiento', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_descarga.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paquetes_descarga_solicitud_id'), 'paquetes_descarga', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paquetes_descarga_solicitud_id'), table_name='paquetes_descarga')
    op.drop_table('paquetes_descarga')
    op.drop_index(op.f('ix_solicitudes_descarga_negocio_id'), table_name='solicitudes_descarga')
    op.drop_index(op.f('ix_solicitudes_descarga_id_solicitud_sat'), table_name='solicitudes_descarga')
    op.drop_index(op.f('ix_solicitudes_descarga_efirma_id'), table_name='solicitudes_descarga')
    op.drop_table('solicitudes_descarga')
    op.drop_index(op.f('ix_efirmas_rfc_titular'), table_name='efirmas')
    op.drop_index(op.f('ix_efirmas_negocio_id'), table_name='efirmas')
    op.drop_table('efirmas')
    # ### end Alembic commands ###
