"""agregar vigencia_csd_hasta a emisores

Revision ID: 72d545d1cbfe
Revises: 455d9f843f76
Create Date: 2026-09-15 11:49:02.341880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d545d1cbfe'
down_revision: Union[str, Sequence[str], None] = '455d9f843f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('vigencia_csd_hasta', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisores', 'vigencia_csd_hasta')
    # ### end Alembic commands ###
