"""emisores color_primario g7VQns

Revision ID: 86da81490e2f
Revises: 02c2b3025be2
Create Date: 2026-09-18 12:56:40.998709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86da81490e2f'
down_revision: Union[str, Sequence[str], None] = '02c2b3025be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('color_primario', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisores', 'color_primario')
    # ### end Alembic commands ###
