"""agregar creado_por_rfc a emisores

Revision ID: 86ec365e82b2
Revises: 5483733620f5
Create Date: 2026-08-10 20:49:59.497730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ec365e82b2'
down_revision: Union[str, Sequence[str], None] = '5483733620f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emisores', sa.Column('creado_por_rfc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emisores', 'creado_por_rfc')
    # ### end Alembic commands ###
