"""efirmas: indice unico parcial 1 Activa por rfc_titular (zg55DWY paso 2)

Revision ID: b44791f20998
Revises: 4f1c844bb8c3
Create Date: 2026-09-09 18:48:53.978435

Autogenerada contra postgres_admin en 4f1c844bb8c3. Una sola operacion:
CREATE UNIQUE INDEX ... WHERE estado = 'Activo'. Sin drift sobre nada mas.
La tabla efirmas esta VACIA (0 filas) - agregar la constraint ahora, antes
de que haya datos reales, es seguro y no requiere backfill.
NO aplicada todavia (pendiente confirmacion explicita).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44791f20998'
down_revision: Union[str, Sequence[str], None] = '4f1c844bb8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_efirmas_rfc_titular_activo_unico', 'efirmas', ['rfc_titular'], unique=True, postgresql_where=sa.text("estado = 'Activo'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_efirmas_rfc_titular_activo_unico', table_name='efirmas', postgresql_where=sa.text("estado = 'Activo'"))
    # ### end Alembic commands ###
