"""efirmas: columnas de consentimiento (zg55DWY paso 3)

Revision ID: c6194443a5e4
Revises: b44791f20998
Create Date: 2026-09-09 21:26:11.804435

Autogenerada contra postgres_admin en b44791f20998. Dos ADD COLUMN
nullables (consentimiento_at DateTime, consentimiento_por_rfc String(20)),
sin default - la tabla efirmas esta vacia, no hay backfill. No toca ninguna
otra tabla ni el indice unico parcial del paso 2.
NO aplicada todavia (pendiente confirmacion / rebuild del contenedor).

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6194443a5e4'
down_revision: Union[str, Sequence[str], None] = 'b44791f20998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('efirmas', sa.Column('consentimiento_at', sa.DateTime(), nullable=True))
    op.add_column('efirmas', sa.Column('consentimiento_por_rfc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('efirmas', 'consentimiento_por_rfc')
    op.drop_column('efirmas', 'consentimiento_at')
    # ### end Alembic commands ###
