"""solicitudes_descarga: codigo_estado_solicitud (zg55DWY fase 2 fix)

Revision ID: cbd62825972e
Revises: 4af7f6b8bbbd
Create Date: 2026-09-10 01:32:17.730926

Autogenerada contra postgres_admin en 4af7f6b8bbbd. Una sola operacion:
ADD COLUMN codigo_estado_solicitud VARCHAR(5) NULL sobre
solicitudes_descarga. Guarda el CodigoEstadoSolicitud que devuelve
VerificaSolicitudDescarga (distinto de cod_estatus / del sobre SOAP) -
descubierto en la corrida real de Fase 2: "sin resultados" llega como
EstadoSolicitud=5 + CodigoEstadoSolicitud=5004, no como EstadoSolicitud=3.
Solo 1 fila real en la tabla (id=9) - sin backfill relevante, queda NULL
al aplicar; el re-test posterior via VerificaSolicitudDescarga la llena
con "5004". Aplicada contra la BD real tras rebuild del contenedor.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd62825972e'
down_revision: Union[str, Sequence[str], None] = '4af7f6b8bbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solicitudes_descarga', sa.Column('codigo_estado_solicitud', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solicitudes_descarga', 'codigo_estado_solicitud')
    # ### end Alembic commands ###
