"""declaraciones anuales documentos PDF

Revision ID: e99c6581cc3d
Revises: 2cce7e6ba51e
Create Date: 2026-09-22 23:38:38.351668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import database


# revision identifiers, used by Alembic.
revision: str = 'e99c6581cc3d'
down_revision: Union[str, Sequence[str], None] = '2cce7e6ba51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('declaraciones_anuales_documentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('emisor_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio', sa.Integer(), nullable=False),
    sa.Column('tipo_declaracion', sa.String(length=20), nullable=False),
    sa.Column('numero_complementaria', sa.Integer(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=30), nullable=False),
    sa.Column('nombre_archivo_original', sa.String(length=255), nullable=False),
    sa.Column('tamano_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('contenido_cifrado', database.CifradoFernetBinario(), nullable=False),
    sa.Column('creado_por', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(tipo_declaracion = 'normal' AND numero_complementaria IS NULL) OR (tipo_declaracion = 'complementaria' AND numero_complementaria BETWEEN 1 AND 3)", name='ck_declaracion_doc_numero_complementaria'),
    sa.CheckConstraint("tipo_declaracion IN ('normal', 'complementaria')", name='ck_declaracion_doc_tipo_declaracion'),
    sa.CheckConstraint("tipo_documento IN ('declaracion', 'acuse', 'comprobante_pago')", name='ck_declaracion_doc_tipo_documento'),
    sa.ForeignKeyConstraint(['emisor_id'], ['emisores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('negocio_id', 'sha256', name='uq_declaracion_doc_negocio_sha256')
    )
    op.create_index(op.f('ix_declaraciones_anuales_documentos_ejercicio'), 'declaraciones_anuales_documentos', ['ejercicio'], unique=False)
    op.create_index(op.f('ix_declaraciones_anuales_documentos_emisor_id'), 'declaraciones_anuales_documentos', ['emisor_id'], unique=False)
    op.create_index(op.f('ix_declaraciones_anuales_documentos_negocio_id'), 'declaraciones_anuales_documentos', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_declaraciones_anuales_documentos_sha256'), 'declaraciones_anuales_documentos', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_declaraciones_anuales_documentos_sha256'), table_name='declaraciones_anuales_documentos')
    op.drop_index(op.f('ix_declaraciones_anuales_documentos_negocio_id'), table_name='declaraciones_anuales_documentos')
    op.drop_index(op.f('ix_declaraciones_anuales_documentos_emisor_id'), table_name='declaraciones_anuales_documentos')
    op.drop_index(op.f('ix_declaraciones_anuales_documentos_ejercicio'), table_name='declaraciones_anuales_documentos')
    op.drop_table('declaraciones_anuales_documentos')
    # ### end Alembic commands ###
