import { useRef, useState } from "react";
import { useToast } from "../../shared/layout/ToastProvider";
import { API_BASE, fetchAuth } from "../../shared/hooks/fetchAuth";
import { Btn, Card, SectionTitle, SectionSub } from "../../shared/components/atoms";
import { C, detalleError } from "../../shared/utils/format";

export default function AltaEmisorForm({ onCreado, onCancelar }) {
  const toast = useToast();
  const [form, setForm] = useState({razon_social:"",rfc:"",regimen_fiscal:"",codigo_postal:"",csd_password:""});
  const [cerFile,setCerFile]=useState(null), [keyFile,setKeyFile]=useState(null), [enviando,setEnviando]=useState(false), [error,setError]=useState(null);
  const cerInputRef=useRef(), keyInputRef=useRef();
  const fileToBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]||"");reader.onerror=()=>reject(new Error("No se pudo leer el archivo"));reader.readAsDataURL(file);});
  const limpiarFormulario=()=>{setForm({razon_social:"",rfc:"",regimen_fiscal:"",codigo_postal:"",csd_password:""});setCerFile(null);setKeyFile(null);if(cerInputRef.current)cerInputRef.current.value="";if(keyInputRef.current)keyInputRef.current.value="";};
  const submit=async e=>{e.preventDefault();setError(null);if(!form.razon_social||!form.rfc||!form.regimen_fiscal||!form.codigo_postal||!form.csd_password){setError("Completa todos los campos antes de continuar.");return;}if(!cerFile||!keyFile){setError("Sube los dos archivos del CSD (.cer y .key).");return;}setEnviando(true);try{const [csd_cert_base64,csd_key_base64]=await Promise.all([fileToBase64(cerFile),fileToBase64(keyFile)]);const res=await fetchAuth(`${API_BASE}/admin/emisores`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,csd_cert_base64,csd_key_base64})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(detalleError(data,res));toast(`Emisor ${data.rfc} registrado correctamente`,"success");limpiarFormulario();onCreado();}catch(e){setError(e.message);toast(`Error al registrar emisor: ${e.message}`,"error");}finally{setEnviando(false);}};
  const inp=(label,key,opts={})=><div style={{marginBottom:12}}><label style={{fontSize:12,color:C.textSec,display:"block",marginBottom:3}}>{label}</label><input type={opts.type||"text"} value={form[key]} maxLength={opts.maxLength} autoComplete="off" onChange={e=>setForm({...form,[key]:opts.upper?e.target.value.toUpperCase():e.target.value})} placeholder={opts.placeholder||label} style={{width:"100%",border:`1px solid ${C.border}`,borderRadius:8,padding:"8px 11px",fontSize:13,color:C.text,background:"#fff",boxSizing:"border-box"}}/></div>;
  return <div><SectionTitle>Emisores</SectionTitle><SectionSub>{onCancelar?"Registra los datos y el CSD del nuevo emisor.":"Todavía no hay ningún emisor registrado — da de alta el primero para poder timbrar."}</SectionSub><Card style={{maxWidth:480}}><form onSubmit={submit} autoComplete="off">{inp("Razón social","razon_social")}{inp("RFC","rfc",{upper:true,maxLength:13,placeholder:"AAAA000101AAA"})}{inp("Régimen fiscal (código SAT)","regimen_fiscal",{maxLength:3,placeholder:"601"})}{inp("Código postal de expedición","codigo_postal",{maxLength:5,placeholder:"00000"})}<div style={{marginBottom:12}}><label style={{fontSize:12,color:C.textSec,display:"block",marginBottom:3}}>Certificado (.cer)</label><input ref={cerInputRef} type="file" accept=".cer" onChange={e=>setCerFile(e.target.files[0]||null)} style={{width:"100%",fontSize:12,color:C.text}}/></div><div style={{marginBottom:12}}><label style={{fontSize:12,color:C.textSec,display:"block",marginBottom:3}}>Llave privada (.key)</label><input ref={keyInputRef} type="file" accept=".key" onChange={e=>setKeyFile(e.target.files[0]||null)} style={{width:"100%",fontSize:12,color:C.text}}/></div><div style={{marginBottom:16}}><label style={{fontSize:12,color:C.textSec,display:"block",marginBottom:3}}>Contraseña del CSD</label><input type="password" value={form.csd_password} autoComplete="new-password" onChange={e=>setForm({...form,csd_password:e.target.value})} style={{width:"100%",border:`1px solid ${C.border}`,borderRadius:8,padding:"8px 11px",fontSize:13,color:C.text,background:"#fff",boxSizing:"border-box"}}/></div>{error&&<div style={{fontSize:12,color:C.danger,marginBottom:14,padding:"8px 10px",background:C.dangerSoft,borderRadius:6}}>⚠ {error}</div>}<div style={{display:"flex",gap:8}}><Btn disabled={enviando} style={{flex:1}}>{enviando?"Registrando…":"Registrar emisor"}</Btn>{onCancelar&&<Btn type="button" variant="secondary" onClick={onCancelar} disabled={enviando}>Cancelar</Btn>}</div></form></Card></div>;
}
