"""agregar numero_cliente a tickets_venta

Revision ID: 1e664602204e
Revises: 2ebc5ec74530
Create Date: 2026-09-05 09:37:59.116747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e664602204e'
down_revision: Union[str, Sequence[str], None] = '2ebc5ec74530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets_venta', sa.Column('numero_cliente', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets_venta', 'numero_cliente')
    # ### end Alembic commands ###
