"""agregar pdf_generado_at a tickets_venta

Revision ID: 2ebc5ec74530
Revises: 8c0a76d37be0
Create Date: 2026-09-04 22:28:15.878766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ebc5ec74530'
down_revision: Union[str, Sequence[str], None] = '8c0a76d37be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets_venta', sa.Column('pdf_generado_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets_venta', 'pdf_generado_at')
    # ### end Alembic commands ###
