"""endurecer negocio_id a NOT NULL en facturas

Revision ID: 325b3eb0c299
Revises: a7b185463b2c
Create Date: 2026-08-07 17:23:36.638089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325b3eb0c299'
down_revision: Union[str, Sequence[str], None] = 'a7b185463b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas', 'negocio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facturas', 'negocio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
