"""agregar costo_timbre a facturas (#6)

Revision ID: 3d9bafd0c575
Revises: a0600d0d4a85
Create Date: 2026-08-04 20:46:12.508870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9bafd0c575'
down_revision: Union[str, Sequence[str], None] = 'a0600d0d4a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('costo_timbre', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'costo_timbre')
    # ### end Alembic commands ###
