"""agregar metodo_pago a facturas para contador virtual (#40)

Revision ID: 589114594e9f
Revises: 3d9bafd0c575
Create Date: 2026-08-05 21:34:03.937974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589114594e9f'
down_revision: Union[str, Sequence[str], None] = '3d9bafd0c575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('metodo_pago', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'metodo_pago')
    # ### end Alembic commands ###
