"""agregar idempotency_key a facturas

Revision ID: 7030042484ed
Revises: 75801745c285
Create Date: 2026-08-18 19:16:52.160244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7030042484ed'
down_revision: Union[str, Sequence[str], None] = '75801745c285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_facturas_idempotency_key'), 'facturas', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_idempotency_key'), table_name='facturas')
    op.drop_column('facturas', 'idempotency_key')
    # ### end Alembic commands ###
