"""agregar creado_por_rfc y cancelado_por_rfc a facturas

Revision ID: 75801745c285
Revises: 325b3eb0c299
Create Date: 2026-08-10 20:42:16.273837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75801745c285'
down_revision: Union[str, Sequence[str], None] = '325b3eb0c299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('creado_por_rfc', sa.String(length=20), nullable=True))
    op.add_column('facturas', sa.Column('cancelado_por_rfc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'cancelado_por_rfc')
    op.drop_column('facturas', 'creado_por_rfc')
    # ### end Alembic commands ###
