"""agregar tickets_venta

Revision ID: 8c0a76d37be0
Revises: b20fc32da8ff
Create Date: 2026-09-04 18:05:59.659920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0a76d37be0'
down_revision: Union[str, Sequence[str], None] = 'b20fc32da8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets_venta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('emisor_rfc', sa.String(length=13), nullable=False),
    sa.Column('folio', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('conceptos', sa.Text(), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rfc_receptor', sa.String(length=13), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('creado_por_rfc', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emisor_rfc', 'folio', name='uq_ticket_venta_emisor_folio')
    )
    op.create_index(op.f('ix_tickets_venta_emisor_rfc'), 'tickets_venta', ['emisor_rfc'], unique=False)
    op.create_index(op.f('ix_tickets_venta_negocio_id'), 'tickets_venta', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_tickets_venta_qr_token'), 'tickets_venta', ['qr_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_venta_qr_token'), table_name='tickets_venta')
    op.drop_index(op.f('ix_tickets_venta_negocio_id'), table_name='tickets_venta')
    op.drop_index(op.f('ix_tickets_venta_emisor_rfc'), table_name='tickets_venta')
    op.drop_table('tickets_venta')
    # ### end Alembic commands ###
