"""agregar negocio_id a facturas (nullable)

Revision ID: a7b185463b2c
Revises: 589114594e9f
Create Date: 2026-08-07 17:21:15.835272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b185463b2c'
down_revision: Union[str, Sequence[str], None] = '589114594e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('negocio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_facturas_negocio_id'), 'facturas', ['negocio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_negocio_id'), table_name='facturas')
    op.drop_column('facturas', 'negocio_id')
    # ### end Alembic commands ###
