"""agregar borradores_factura_eliminados

Revision ID: b20fc32da8ff
Revises: ff1c93bf7759
Create Date: 2026-09-01 04:20:29.356391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20fc32da8ff'
down_revision: Union[str, Sequence[str], None] = 'ff1c93bf7759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borradores_factura_eliminados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('borrador_id_original', sa.Integer(), nullable=False),
    sa.Column('emisor_rfc', sa.String(length=13), nullable=True),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('creado_por_rfc', sa.String(length=20), nullable=True),
    sa.Column('eliminado_por_rfc', sa.String(length=20), nullable=True),
    sa.Column('motivo', sa.String(length=20), nullable=False),
    sa.Column('creado_en_original', sa.DateTime(), nullable=False),
    sa.Column('eliminado_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borradores_factura_eliminados_borrador_id_original'), 'borradores_factura_eliminados', ['borrador_id_original'], unique=False)
    op.create_index(op.f('ix_borradores_factura_eliminados_negocio_id'), 'borradores_factura_eliminados', ['negocio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borradores_factura_eliminados_negocio_id'), table_name='borradores_factura_eliminados')
    op.drop_index(op.f('ix_borradores_factura_eliminados_borrador_id_original'), table_name='borradores_factura_eliminados')
    op.drop_table('borradores_factura_eliminados')
    # ### end Alembic commands ###
