"""agregar ticket_id a facturas (vinculo con TicketVenta, zg5b-ZE pieza 5)

Revision ID: bdc1346b9894
Revises: 1e664602204e
Create Date: 2026-09-05 23:12:50.623053

ORDEN DE DEPLOY OBLIGATORIO: esta migracion debe aplicarse
(alembic upgrade head) ANTES o EN EL MISMO PASO que el rebuild/restart del
contenedor de facturacion con el codigo que escribe Factura.ticket_id -
NUNCA despues. Si el contenedor arranca con el codigo nuevo mientras la
columna ticket_id todavia no existe en la BD real, CADA llamada a
_ejecutar_timbrado (incluyendo timbrar_factura, el endpoint manual
existente, no solo la pieza 5) fallara el commit de Factura y caera en el
except tragon que ya existe - Finkok SI timbrara, pero NINGUNA factura se
guardaria en la tabla facturas hasta corregir esto.

CONFIRMADO (05 sep 2026): facturacion NO aplica migraciones pendientes al
arrancar. El lifespan de main.py solo corre create_tables()
(Base.metadata.create_all - crea tablas nuevas, NUNCA altera una que ya
existe, asi que NO agrega esta columna) y stamp_head_si_es_ambiente_nuevo()
(que hace 'alembic stamp head' SOLO si la tabla alembic_version no existe;
en un ambiente con historia real - como este, head=1e664602204e - retorna
de inmediato sin hacer nada). Aplicar esta migracion requiere un
`alembic upgrade head` MANUAL y deliberado, por diseño (ver docstring de
stamp_head_si_es_ambiente_nuevo en database.py).

Comando para aplicarla (Windows git-bash, mismo patron que las 3
migraciones anteriores de esta pieza):
    MSYS_NO_PATHCONV=1 docker compose run --rm --no-deps \
      -v "$(pwd)/backend/microservices/facturacion/alembic/versions:/app/alembic/versions" \
      facturacion alembic upgrade head
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc1346b9894'
down_revision: Union[str, Sequence[str], None] = '1e664602204e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('ticket_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_facturas_ticket_id'), 'facturas', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_ticket_id'), table_name='facturas')
    op.drop_column('facturas', 'ticket_id')
    # ### end Alembic commands ###
