"""ticketventa forma_pago g7r6Uc

Revision ID: d769ac708caa
Revises: fd37bf963bc8
Create Date: 2026-09-18 21:14:39.078509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd769ac708caa'
down_revision: Union[str, Sequence[str], None] = 'fd37bf963bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets_venta', sa.Column('forma_pago', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets_venta', 'forma_pago')
    # ### end Alembic commands ###
