"""factura_consolidacion_tickets (g5b-kc)

Revision ID: fd37bf963bc8
Revises: bdc1346b9894
Create Date: 2026-09-18 03:59:32.091953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd37bf963bc8'
down_revision: Union[str, Sequence[str], None] = 'bdc1346b9894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura_consolidacion_tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_consolidacion_tickets_factura_id'), 'factura_consolidacion_tickets', ['factura_id'], unique=False)
    op.create_index(op.f('ix_factura_consolidacion_tickets_ticket_id'), 'factura_consolidacion_tickets', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_factura_consolidacion_tickets_ticket_id'), table_name='factura_consolidacion_tickets')
    op.drop_index(op.f('ix_factura_consolidacion_tickets_factura_id'), table_name='factura_consolidacion_tickets')
    op.drop_table('factura_consolidacion_tickets')
    # ### end Alembic commands ###
