"""agregar borradores_factura

Revision ID: ff1c93bf7759
Revises: 7030042484ed
Create Date: 2026-08-27 23:40:46.361275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1c93bf7759'
down_revision: Union[str, Sequence[str], None] = '7030042484ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borradores_factura',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('emisor_rfc', sa.String(length=13), nullable=True),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('creado_por_rfc', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borradores_factura_emisor_rfc'), 'borradores_factura', ['emisor_rfc'], unique=False)
    op.create_index(op.f('ix_borradores_factura_negocio_id'), 'borradores_factura', ['negocio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_borradores_factura_negocio_id'), table_name='borradores_factura')
    op.drop_index(op.f('ix_borradores_factura_emisor_rfc'), table_name='borradores_factura')
    op.drop_table('borradores_factura')
    # ### end Alembic commands ###
