"""agregar rfc_personal a usuarios

Revision ID: 28de11d5b1ac
Revises: e9afed110f77
Create Date: 2026-08-07 15:11:29.354580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28de11d5b1ac'
down_revision: Union[str, Sequence[str], None] = 'e9afed110f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rfc_personal', sa.String(length=13), nullable=False))
    op.create_index(op.f('ix_usuarios_rfc_personal'), 'usuarios', ['rfc_personal'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_rfc_personal'), table_name='usuarios')
    op.drop_column('usuarios', 'rfc_personal')
    # ### end Alembic commands ###
