"""agregar usuario a usuarios

Revision ID: 65704c55d5f8
Revises: 28de11d5b1ac
Create Date: 2026-08-10 22:56:24.121480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65704c55d5f8'
down_revision: Union[str, Sequence[str], None] = '28de11d5b1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('usuario', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'usuarios', ['usuario'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_column('usuarios', 'usuario')
    # ### end Alembic commands ###
