"""agregar usuarios.negocio_id nullable (#15)

Revision ID: ccc26c057d96
Revises: b2617776cb8d
Create Date: 2026-08-06 18:31:32.119107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc26c057d96'
down_revision: Union[str, Sequence[str], None] = 'b2617776cb8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('negocio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_usuarios_negocio_id'), 'usuarios', ['negocio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_negocio_id'), table_name='usuarios')
    op.drop_column('usuarios', 'negocio_id')
    # ### end Alembic commands ###
