"""endurecer usuarios.negocio_id a NOT NULL (#15)

Revision ID: e9afed110f77
Revises: ccc26c057d96
Create Date: 2026-08-06 18:43:58.499139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9afed110f77'
down_revision: Union[str, Sequence[str], None] = 'ccc26c057d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'negocio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'negocio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
